In [ ]:
# curl --request GET \
# 	--url https://instagram120.p.rapidapi.com/api/instagram/hls \
# 	--header 'x-rapidapi-host: instagram120.p.rapidapi.com' \
# 	--header 'x-rapidapi-key: 60ea375277msh6b015475d6b6e72p11791ajsneed1092b3bef'

In [12]:
import requests
import json
import pandas as pd

In [6]:
# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&apikey=6TOT9GKVOY1CEN74'
r = requests.get(url)
data = r.json()

print(data)

{'Meta Data': {'1. Information': 'Intraday (5min) open, high, low, close prices and volume', '2. Symbol': 'IBM', '3. Last Refreshed': '2025-05-23 19:55:00', '4. Interval': '5min', '5. Output Size': 'Compact', '6. Time Zone': 'US/Eastern'}, 'Time Series (5min)': {'2025-05-23 19:55:00': {'1. open': '258.0100', '2. high': '258.0100', '3. low': '258.0100', '4. close': '258.0100', '5. volume': '2'}, '2025-05-23 19:50:00': {'1. open': '258.4000', '2. high': '258.4000', '3. low': '258.4000', '4. close': '258.4000', '5. volume': '20'}, '2025-05-23 19:45:00': {'1. open': '258.0000', '2. high': '258.4000', '3. low': '258.0000', '4. close': '258.4000', '5. volume': '31'}, '2025-05-23 19:30:00': {'1. open': '258.9900', '2. high': '258.9900', '3. low': '258.9900', '4. close': '258.9900', '5. volume': '5'}, '2025-05-23 19:25:00': {'1. open': '258.9900', '2. high': '258.9900', '3. low': '258.9900', '4. close': '258.9900', '5. volume': '2'}, '2025-05-23 19:15:00': {'1. open': '258.6500', '2. high': '258.6500', '3. low': '258.6500', '4. close': '258.6500', '5. volume': '1'}, '2025-05-23 19:05:00': {'1. open': '258.6500', '2. high': '258.6500', '3. low': '258.6500', '4. close': '258.6500', '5. volume': '1'}, '2025-05-23 19:00:00': {'1. open': '258.6300', '2. high': '258.6300', '3. low': '258.6300', '4. close': '258.6300', '5. volume': '351523'}, '2025-05-23 18:55:00': {'1. open': '258.7000', '2. high': '258.7000', '3. low': '258.5000', '4. close': '258.6300', '5. volume': '3'}, '2025-05-23 18:45:00': {'1. open': '258.0100', '2. high': '258.9900', '3. low': '258.0100', '4. close': '258.9900', '5. volume': '8'}, '2025-05-23 18:30:00': {'1. open': '258.6300', '2. high': '258.6300', '3. low': '258.6300', '4. close': '258.6300', '5. volume': '351523'}, '2025-05-23 18:25:00': {'1. open': '258.0100', '2. high': '258.0100', '3. low': '258.0100', '4. close': '258.0100', '5. volume': '2'}, '2025-05-23 18:20:00': {'1. open': '258.7400', '2. high': '258.7400', '3. low': '258.7400', '4. close': '258.7400', '5. volume': '1'}, '2025-05-23 18:10:00': {'1. open': '258.7400', '2. high': '258.7400', '3. low': '258.7400', '4. close': '258.7400', '5. volume': '10'}, '2025-05-23 18:00:00': {'1. open': '258.8000', '2. high': '258.8000', '3. low': '258.0000', '4. close': '258.0000', '5. volume': '11'}, '2025-05-23 17:55:00': {'1. open': '258.5000', '2. high': '258.6000', '3. low': '258.5000', '4. close': '258.6000', '5. volume': '2'}, '2025-05-23 17:50:00': {'1. open': '258.5600', '2. high': '258.9900', '3. low': '258.5600', '4. close': '258.9900', '5. volume': '2'}, '2025-05-23 17:35:00': {'1. open': '257.5800', '2. high': '258.5000', '3. low': '257.5800', '4. close': '258.5000', '5. volume': '3'}, '2025-05-23 17:30:00': {'1. open': '258.5000', '2. high': '258.5000', '3. low': '258.5000', '4. close': '258.5000', '5. volume': '1'}, '2025-05-23 17:25:00': {'1. open': '258.0100', '2. high': '258.6300', '3. low': '257.9900', '4. close': '258.0100', '5. volume': '6051'}, '2025-05-23 17:20:00': {'1. open': '259.0000', '2. high': '259.0000', '3. low': '259.0000', '4. close': '259.0000', '5. volume': '3'}, '2025-05-23 17:15:00': {'1. open': '258.0600', '2. high': '258.0600', '3. low': '258.0600', '4. close': '258.0600', '5. volume': '1'}, '2025-05-23 17:00:00': {'1. open': '258.3000', '2. high': '259.0000', '3. low': '257.0000', '4. close': '259.0000', '5. volume': '63'}, '2025-05-23 16:55:00': {'1. open': '258.3300', '2. high': '258.9019', '3. low': '258.3000', '4. close': '258.3000', '5. volume': '225'}, '2025-05-23 16:40:00': {'1. open': '257.0000', '2. high': '258.6300', '3. low': '257.0000', '4. close': '257.1000', '5. volume': '4172'}, '2025-05-23 16:35:00': {'1. open': '258.0000', '2. high': '258.0100', '3. low': '258.0000', '4. close': '258.0100', '5. volume': '3'}, '2025-05-23 16:30:00': {'1. open': '257.0000', '2. high': '257.0000', '3. low': '257.0000', '4. close': '257.0000', '5. volume': '9'}, '2025-05-23 16:25:00': {'1. open': '258.6300', '2. high': '259.0000', '3. low': '256.4000', '4. close': '258.6300', '5. volume': '16436'}, '2025-05-23 16:20:00': {'1. open': '258.5600', '2. high': '258.5600', '3. low': '258.5600', '4. close': '258.5600', '5. volume': '3'}, '2025-05-23 16:15:00': {'1. open': '258.6300', '2. high': '258.6300', '3. low': '258.5600', '4. close': '258.5600', '5. volume': '3'}, '2025-05-23 16:10:00': {'1. open': '258.6300', '2. high': '258.6300', '3. low': '256.3800', '4. close': '256.6400', '5. volume': '352195'}, '2025-05-23 16:00:00': {'1. open': '258.7100', '2. high': '258.9900', '3. low': '254.9500', '4. close': '258.6300', '5. volume': '808070'}, '2025-05-23 15:55:00': {'1. open': '258.8100', '2. high': '259.0900', '3. low': '258.5300', '4. close': '258.6300', '5. volume': '156754'}, '2025-05-23 15:50:00': {'1. open': '259.3900', '2. high': '259.4400', '3. low': '258.6550', '4. close': '258.8650', '5. volume': '67431'}, '2025-05-23 15:45:00': {'1. open': '259.4765', '2. high': '259.4850', '3. low': '259.2300', '4. close': '259.3150', '5. volume': '43557'}, '2025-05-23 15:40:00': {'1. open': '259.3800', '2. high': '259.6000', '3. low': '259.3600', '4. close': '259.4800', '5. volume': '24554'}, '2025-05-23 15:35:00': {'1. open': '259.2700', '2. high': '259.4100', '3. low': '259.1000', '4. close': '259.3975', '5. volume': '28150'}, '2025-05-23 15:30:00': {'1. open': '258.9200', '2. high': '259.2400', '3. low': '258.9100', '4. close': '259.2400', '5. volume': '22628'}, '2025-05-23 15:25:00': {'1. open': '259.0200', '2. high': '259.0400', '3. low': '258.8500', '4. close': '258.9650', '5. volume': '15858'}, '2025-05-23 15:20:00': {'1. open': '259.1800', '2. high': '259.2300', '3. low': '258.8300', '4. close': '259.0550', '5. volume': '23392'}, '2025-05-23 15:15:00': {'1. open': '259.4381', '2. high': '259.4400', '3. low': '259.1200', '4. close': '259.1800', '5. volume': '22973'}, '2025-05-23 15:10:00': {'1. open': '259.2350', '2. high': '259.4500', '3. low': '259.2100', '4. close': '259.4150', '5. volume': '15346'}, '2025-05-23 15:05:00': {'1. open': '259.1000', '2. high': '259.3300', '3. low': '258.9900', '4. close': '259.2225', '5. volume': '27150'}, '2025-05-23 15:00:00': {'1. open': '259.2593', '2. high': '259.2593', '3. low': '259.0100', '4. close': '259.1000', '5. volume': '16205'}, '2025-05-23 14:55:00': {'1. open': '259.4100', '2. high': '259.4100', '3. low': '259.1300', '4. close': '259.2300', '5. volume': '11580'}, '2025-05-23 14:50:00': {'1. open': '259.4350', '2. high': '259.5200', '3. low': '259.3400', '4. close': '259.4100', '5. volume': '12691'}, '2025-05-23 14:45:00': {'1. open': '259.4258', '2. high': '259.4400', '3. low': '259.2800', '4. close': '259.4200', '5. volume': '12607'}, '2025-05-23 14:40:00': {'1. open': '259.5900', '2. high': '259.6850', '3. low': '259.3800', '4. close': '259.3950', '5. volume': '16263'}, '2025-05-23 14:35:00': {'1. open': '259.7500', '2. high': '259.8696', '3. low': '259.5400', '4. close': '259.6000', '5. volume': '18893'}, '2025-05-23 14:30:00': {'1. open': '259.5900', '2. high': '259.7200', '3. low': '259.5000', '4. close': '259.6200', '5. volume': '9153'}, '2025-05-23 14:25:00': {'1. open': '259.4400', '2. high': '259.6550', '3. low': '259.3000', '4. close': '259.5697', '5. volume': '15311'}, '2025-05-23 14:20:00': {'1. open': '259.2300', '2. high': '259.4800', '3. low': '259.0900', '4. close': '259.4350', '5. volume': '25410'}, '2025-05-23 14:15:00': {'1. open': '259.4886', '2. high': '259.5300', '3. low': '259.1900', '4. close': '259.2600', '5. volume': '23339'}, '2025-05-23 14:10:00': {'1. open': '259.4100', '2. high': '259.4300', '3. low': '259.2950', '4. close': '259.3800', '5. volume': '10176'}, '2025-05-23 14:05:00': {'1. open': '259.4800', '2. high': '259.6100', '3. low': '259.4000', '4. close': '259.4100', '5. volume': '14326'}, '2025-05-23 14:00:00': {'1. open': '259.5085', '2. high': '259.5600', '3. low': '259.4100', '4. close': '259.4750', '5. volume': '13711'}, '2025-05-23 13:55:00': {'1. open': '259.5150', '2. high': '259.5799', '3. low': '259.3100', '4. close': '259.4250', '5. volume': '10827'}, '2025-05-23 13:50:00': {'1. open': '259.6400', '2. high': '259.6800', '3. low': '259.4400', '4. close': '259.5150', '5. volume': '22962'}, '2025-05-23 13:45:00': {'1. open': '259.2950', '2. high': '259.6150', '3. low': '259.2400', '4. close': '259.6150', '5. volume': '21685'}, '2025-05-23 13:40:00': {'1. open': '259.2500', '2. high': '259.3400', '3. low': '259.1700', '4. close': '259.3400', '5. volume': '13994'}, '2025-05-23 13:35:00': {'1. open': '259.3021', '2. high': '259.3900', '3. low': '259.2000', '4. close': '259.3050', '5. volume': '12916'}, '2025-05-23 13:30:00': {'1. open': '259.5113', '2. high': '259.5113', '3. low': '259.2500', '4. close': '259.2750', '5. volume': '23858'}, '2025-05-23 13:25:00': {'1. open': '259.4607', '2. high': '259.5300', '3. low': '259.3400', '4. close': '259.4600', '5. volume': '16903'}, '2025-05-23 13:20:00': {'1. open': '259.3800', '2. high': '259.4500', '3. low': '259.3300', '4. close': '259.4500', '5. volume': '8533'}, '2025-05-23 13:15:00': {'1. open': '258.9500', '2. high': '259.4825', '3. low': '258.9400', '4. close': '259.3800', '5. volume': '13946'}, '2025-05-23 13:10:00': {'1. open': '258.9200', '2. high': '258.9950', '3. low': '258.7700', '4. close': '258.9000', '5. volume': '24057'}, '2025-05-23 13:05:00': {'1. open': '258.8300', '2. high': '258.9200', '3. low': '258.7388', '4. close': '258.9200', '5. volume': '13043'}, '2025-05-23 13:00:00': {'1. open': '258.2400', '2. high': '258.8500', '3. low': '258.1500', '4. close': '258.7800', '5. volume': '39733'}, '2025-05-23 12:55:00': {'1. open': '258.4900', '2. high': '258.4900', '3. low': '258.1300', '4. close': '258.2300', '5. volume': '13767'}, '2025-05-23 12:50:00': {'1. open': '258.4700', '2. high': '258.5100', '3. low': '258.3700', '4. close': '258.4800', '5. volume': '12139'}, '2025-05-23 12:45:00': {'1. open': '258.3600', '2. high': '258.4900', '3. low': '258.3000', '4. close': '258.4500', '5. volume': '10377'}, '2025-05-23 12:40:00': {'1. open': '258.5700', '2. high': '258.6600', '3. low': '258.3600', '4. close': '258.3600', '5. volume': '10906'}, '2025-05-23 12:35:00': {'1. open': '258.0900', '2. high': '258.6700', '3. low': '258.0900', '4. close': '258.6300', '5. volume': '23327'}, '2025-05-23 12:30:00': {'1. open': '258.2200', '2. high': '258.2200', '3. low': '257.9400', '4. close': '258.0500', '5. volume': '17066'}, '2025-05-23 12:25:00': {'1. open': '258.3600', '2. high': '258.4800', '3. low': '258.2100', '4. close': '258.2100', '5. volume': '22947'}, '2025-05-23 12:20:00': {'1. open': '258.0600', '2. high': '258.4400', '3. low': '258.0600', '4. close': '258.3800', '5. volume': '21370'}, '2025-05-23 12:15:00': {'1. open': '257.9600', '2. high': '258.2172', '3. low': '257.9600', '4. close': '258.0600', '5. volume': '17873'}, '2025-05-23 12:10:00': {'1. open': '257.9400', '2. high': '258.0499', '3. low': '257.8800', '4. close': '257.9100', '5. volume': '13986'}, '2025-05-23 12:05:00': {'1. open': '257.8800', '2. high': '258.1300', '3. low': '257.7250', '4. close': '257.9500', '5. volume': '38140'}, '2025-05-23 12:00:00': {'1. open': '257.8450', '2. high': '258.2950', '3. low': '257.8300', '4. close': '257.8800', '5. volume': '61026'}, '2025-05-23 11:55:00': {'1. open': '258.0800', '2. high': '258.1950', '3. low': '257.8400', '4. close': '257.8800', '5. volume': '46379'}, '2025-05-23 11:50:00': {'1. open': '258.6000', '2. high': '258.6000', '3. low': '258.0800', '4. close': '258.0900', '5. volume': '17972'}, '2025-05-23 11:45:00': {'1. open': '258.6800', '2. high': '258.7679', '3. low': '258.5000', '4. close': '258.5600', '5. volume': '18155'}, '2025-05-23 11:40:00': {'1. open': '258.6600', '2. high': '258.8200', '3. low': '258.5700', '4. close': '258.7449', '5. volume': '11162'}, '2025-05-23 11:35:00': {'1. open': '258.4000', '2. high': '258.8250', '3. low': '258.2400', '4. close': '258.7200', '5. volume': '48125'}, '2025-05-23 11:30:00': {'1. open': '258.0900', '2. high': '258.3800', '3. low': '258.0900', '4. close': '258.3800', '5. volume': '16280'}, '2025-05-23 11:25:00': {'1. open': '258.1700', '2. high': '258.2700', '3. low': '257.9500', '4. close': '258.1550', '5. volume': '21713'}, '2025-05-23 11:20:00': {'1. open': '257.6700', '2. high': '258.1700', '3. low': '257.6500', '4. close': '258.1700', '5. volume': '61475'}, '2025-05-23 11:15:00': {'1. open': '257.4500', '2. high': '257.8300', '3. low': '257.3300', '4. close': '257.6900', '5. volume': '17140'}, '2025-05-23 11:10:00': {'1. open': '257.6400', '2. high': '257.7400', '3. low': '257.3400', '4. close': '257.5300', '5. volume': '24972'}, '2025-05-23 11:05:00': {'1. open': '257.3900', '2. high': '257.6300', '3. low': '257.1800', '4. close': '257.6174', '5. volume': '24537'}, '2025-05-23 11:00:00': {'1. open': '257.1400', '2. high': '257.6200', '3. low': '256.9400', '4. close': '257.4000', '5. volume': '82660'}, '2025-05-23 10:55:00': {'1. open': '257.3250', '2. high': '257.5100', '3. low': '257.0700', '4. close': '257.0750', '5. volume': '73536'}, '2025-05-23 10:50:00': {'1. open': '257.8200', '2. high': '257.9050', '3. low': '257.3900', '4. close': '257.3900', '5. volume': '31498'}, '2025-05-23 10:45:00': {'1. open': '257.8050', '2. high': '258.2000', '3. low': '257.7200', '4. close': '257.8800', '5. volume': '54722'}, '2025-05-23 10:40:00': {'1. open': '258.0300', '2. high': '258.2650', '3. low': '257.7200', '4. close': '257.7500', '5. volume': '34609'}, '2025-05-23 10:35:00': {'1. open': '257.8400', '2. high': '258.1400', '3. low': '257.6900', '4. close': '258.0500', '5. volume': '22022'}, '2025-05-23 10:30:00': {'1. open': '257.5100', '2. high': '257.8500', '3. low': '257.2300', '4. close': '257.8300', '5. volume': '18065'}, '2025-05-23 10:25:00': {'1. open': '257.6200', '2. high': '257.8200', '3. low': '257.1900', '4. close': '257.3800', '5. volume': '19251'}, '2025-05-23 10:20:00': {'1. open': '257.3150', '2. high': '257.6182', '3. low': '257.2500', '4. close': '257.5550', '5. volume': '24855'}}}

In [13]:
pd.DataFrame.from_dict(data['Time Series (5min)'], orient='index')

                      1. open   2. high    3. low  4. close 5. volume
2025-05-23 19:55:00  258.0100  258.0100  258.0100  258.0100         2
2025-05-23 19:50:00  258.4000  258.4000  258.4000  258.4000        20
2025-05-23 19:45:00  258.0000  258.4000  258.0000  258.4000        31
2025-05-23 19:30:00  258.9900  258.9900  258.9900  258.9900         5
2025-05-23 19:25:00  258.9900  258.9900  258.9900  258.9900         2
...                       ...       ...       ...       ...       ...
2025-05-23 10:40:00  258.0300  258.2650  257.7200  257.7500     34609
2025-05-23 10:35:00  257.8400  258.1400  257.6900  258.0500     22022
2025-05-23 10:30:00  257.5100  257.8500  257.2300  257.8300     18065
2025-05-23 10:25:00  257.6200  257.8200  257.1900  257.3800     19251
2025-05-23 10:20:00  257.3150  257.6182  257.2500  257.5550     24855

[100 rows x 5 columns]